"""Измнение mapped_column, rent_type, pyment_type изменен name

Revision ID: 992c930c7afc
Revises: 166aba2d74ea
Create Date: 2024-04-11 20:37:11.720890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '992c930c7afc'
down_revision = '166aba2d74ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartmens', schema=None) as batch_op:
        batch_op.alter_column('accommodation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comfort_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('propertie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=164),
               nullable=False)
        batch_op.alter_column('rent_type',
               existing_type=postgresql.ENUM('apartment', 'house', 'room', 'hotel', name='apartmenstypechoice'),
               type_=postgresql.ENUM('Не определено', 'Квартира', 'Дом', 'Комната', 'Отель', name='apartmenstypechoice'),
               existing_nullable=False)
        batch_op.alter_column('payment_type',
               existing_type=postgresql.ENUM('cash', 'card', name='paymenstypechoice'),
               type_=postgresql.ENUM('Не определено', 'Наличные', 'Карта', name='paymenstypechoice'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartmens', schema=None) as batch_op:
        batch_op.alter_column('payment_type',
               existing_type=postgresql.ENUM('Не определено', 'Наличные', 'Карта', name='paymenstypechoice'),
               type_=postgresql.ENUM('cash', 'card', name='paymenstypechoice'),
               existing_nullable=False)
        batch_op.alter_column('rent_type',
               existing_type=postgresql.ENUM('Не определено', 'Квартира', 'Дом', 'Комната', 'Отель', name='apartmenstypechoice'),
               type_=postgresql.ENUM('apartment', 'house', 'room', 'hotel', name='apartmenstypechoice'),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=164),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('propertie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('comfort_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('accommodation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
