"""Добавление полей изменение Enum на обычние поля для кнопок Switch

Revision ID: fde78c91fe4a
Revises: 992c930c7afc
Create Date: 2024-04-22 16:48:00.708275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fde78c91fe4a'
down_revision = '992c930c7afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    with op.batch_alter_table('comforts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wi_fi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hair_dryer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('towels', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('balcony', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('air_conditioner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tv', sa.Boolean(), nullable=True))
        batch_op.drop_column('comfort_choice')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('apartment_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('number_of_beds', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('number_of_guests', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('room_area', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('no_children', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('no_parties', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('no_smoking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('no_pets', sa.Boolean(), nullable=True))
        batch_op.drop_column('propertie_choice')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propertie_choice', postgresql.ENUM('no_children', 'no_parties', 'no_smoking', 'no_pets', name='propertiechoise'), autoincrement=False, nullable=False))
        batch_op.drop_column('no_pets')
        batch_op.drop_column('no_smoking')
        batch_op.drop_column('no_parties')
        batch_op.drop_column('no_children')
        batch_op.drop_column('room_area')
        batch_op.drop_column('number_of_guests')
        batch_op.drop_column('number_of_beds')
        batch_op.drop_column('apartment_number')
        batch_op.drop_column('floor')

    with op.batch_alter_table('comforts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comfort_choice', postgresql.ENUM('wi_fi', 'hair_dryer', 'towels', 'balcony', 'air_conditioner', 'tv', name='comfortchoice'), autoincrement=False, nullable=False))
        batch_op.drop_column('tv')
        batch_op.drop_column('air_conditioner')
        batch_op.drop_column('balcony')
        batch_op.drop_column('towels')
        batch_op.drop_column('hair_dryer')
        batch_op.drop_column('wi_fi')

    op.create_table('association_table',
    sa.Column('apartmens_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accommodations_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comforts_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payments_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('properties_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comments_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['accommodations_id'], ['accommodations.id'], name='association_table_accommodations_id_fkey'),
    sa.ForeignKeyConstraint(['apartmens_id'], ['apartmens.id'], name='association_table_apartmens_id_fkey'),
    sa.ForeignKeyConstraint(['comforts_id'], ['comforts.id'], name='association_table_comforts_id_fkey'),
    sa.ForeignKeyConstraint(['comments_id'], ['comments.id'], name='association_table_comments_id_fkey'),
    sa.ForeignKeyConstraint(['payments_id'], ['payments.id'], name='association_table_payments_id_fkey'),
    sa.ForeignKeyConstraint(['properties_id'], ['properties.id'], name='association_table_properties_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='association_table_users_id_fkey'),
    sa.PrimaryKeyConstraint('apartmens_id', 'accommodations_id', 'comforts_id', 'payments_id', 'properties_id', 'comments_id', 'users_id', name='association_table_pkey')
    )
    # ### end Alembic commands ###
